name: Crack the Code
title: Crack the Code | Sujin's CS Portfolio
description: Sujin's Project Archieve
tags:
  - Android
  - Node.js
  - Web
  - App
  - Game
  - Python
  - Research
  - Blog
 
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: waterjin326@gmail.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 
